import type { DefaultValues } from "react-hook-form";
import type { WizardFormData } from "./schema";

export const defaultValues: DefaultValues<WizardFormData> = {
  // ── Sectie 1: Bedrijfsprofiel ────────────────────────────────────────────
  email: "",
  naam: "",
  functie: "",
  telefoon: "",
  linkedin: "",
  bedrijfsnaam: "",
  kvk: "",
  website: "",
  vestigingsplaats: "",
  aantalVestigingen: "",
  sector: "",
  bedrijfsBeschrijving: "",
  jaaromzet: "",
  aantalMedewerkers: "",
  bedrijfsStructuur: "",

  // ── Sectie 2: Processen ──────────────────────────────────────────────────
  processen: [
    {
      procesNaam: "",
      afdeling: "",
      stapVoorStap: "",
      aantalMensen: "",
      tools: "",
      kostenPerFout: "",
    },
  ],

  // ── Sectie 3: Pijnpunten ─────────────────────────────────────────────────
  drieGrootsFrustraties: "",
  tijdVerliesPerWeek: "",
  repetitieveTaken: [],
  percentageRepetitief: "",
  waarGaanFoutenMis: "",
  gevolgFouten: [],
  foutKostenPerMaand: "",
  bedrijfsgroei: "",
  watAlsOmzetVerdubbelt: "",
  bottlenecksGroei: "",
  personeelTekort: "",

  // ── Sectie 4: Data & Informatiebeheer ────────────────────────────────────
  informatieWaarLeeft: [],
  dataConsistentie: "",
  dataVertrouwen: "",
  dataSoorten: [],
  inzichtBedrijfsprestaties: [],
  metricsGoedZicht: "",
  metricsBeterInzicht: "",
  rapportageDuur: "",
  documentenBeheer: [],
  documentZoekenDuur: "",

  // ── Sectie 5: Technologie ────────────────────────────────────────────────
  erpGebruik: "nee",
  erpNaam: "",
  crmGebruik: "nee",
  crmNaam: "",
  boekhoudsoftware: [],
  planningsoplossing: "",
  planningsSoftwareNaam: "",
  dagelijkseTools: [],
  interneCommunicatie: [],
  aantalSystemen: "",
  integraties: "",
  handmatigeDataOverzet: "",
  automatiseringsErvaring: "",
  itVolwassenheid: "",

  // ── Sectie 6: Klant & Sales ──────────────────────────────────────────────
  salesProces: "",
  leadTotDealDoorlooptijd: "",
  conversieratio: "",
  leadsAfhaakpunt: "",
  tijdOftesPerWeek: "",
  klantvragenPerDag: "",
  reactietijdKlant: "",
  soortKlantvragen: [],
  klanttevredenheidNPS: "",
  klantretentie: "",
  aantalActieveKlanten: "",
  klantsegmentatie: "",
  upsellCrossSell: "",

  // ── Sectie 7: Team & HR ──────────────────────────────────────────────────
  bedrijfsOrganisatie: "",
  aanwezigeRollen: [],
  percentageRepetitieveWerkers: "",
  sleutelmedewerkerRisico: "",
  onboardingDuur: "",
  onboardingGestandaardiseerd: "",
  teamHoudingAI: "",
  technischeAffiniteit: "",
  gebruiksgemakBelang: "",

  // ── Sectie 8: Financieel & ROI ───────────────────────────────────────────
  grootsteKostenpost: "",
  brutomarge: "",
  gemiddeldUurtarief: "",
  budgetAI: "",
  roiBeoordeling: "",
  eerdereInvesteringen: "",
  waarde40Uur: "",
  bewijsSuccesAI: [],

  // ── Sectie 9: AI-Gereedheid ──────────────────────────────────────────────
  huidigeAITools: [],
  aiGebruikWijze: [],
  agentBegrip: "",
  automatiseringsKandidaten: [],
  comfortNiveauAI: "",
  dataToegangAI: [],
  sectorRegelgeving: "",
  klantdataPrivacy: [],
  aiTraceerbaarheid: "",

  // ── Sectie 10: Strategie & Visie ─────────────────────────────────────────
  belangrijksteDoel: "",
  topPrioriteiten: [],
  grootsteImpact: "",
  eersteResultatenTimeline: "",
  bedrijfOver3Jaar: "",
  rolAIToekomst: "",
  aiExpertiseBeslissing: "",
  samenwerkingsVorm: "",
  startSnelheid: "",
  aanleiding: "",
  eerderAIBureaus: "",
  bijzonderheden: "",
  hoeGevonden: "",
};
