import type { WizardFormData } from "./schema";

export function formatRapport(data: WizardFormData): string {
  const d = new Date().toLocaleDateString("nl-NL", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const r = (v: string | undefined | null) => v?.trim() || "—";
  const arr = (v: string[] | undefined | null) =>
    v?.length ? v.join(", ") : "—";
  const rating = (v: string | undefined | null) => (v ? `${v}/5` : "—");

  const TIJD: Record<string, string> = {
    lt10uur: "< 10 uur/maand",
    "10_30uur": "10–30 uur/maand",
    "30_60uur": "30–60 uur/maand",
    "60_100uur": "60–100 uur/maand",
    "100_200uur": "100–200 uur/maand",
    gt200uur: "> 200 uur/maand",
  };
  const FOUTEN: Record<string, string> = {
    zelden: "Zelden (< 5%)",
    soms: "Soms (5–15%)",
    regelmatig: "Regelmatig (15–30%)",
    vaak: "Vaak (> 30%)",
  };
  const DOC: Record<string, string> = {
    volledig: "Volledig gedocumenteerd",
    gedeeltelijk: "Gedeeltelijk gedocumenteerd",
    hoofden: "In hoofden van mensen",
    geen: "Geen documentatie",
  };
  const ERP: Record<string, string> = {
    ja: "Ja",
    nee: "Nee",
    zoeken: "Nog niet, maar aan het zoeken",
  };
  const CRM: Record<string, string> = {
    ja: "Ja",
    nee: "Nee",
    excel: "Nee, alleen Excel/sheets",
  };

  const lines: string[] = [
    `NEXTRIQ AI INTELLIGENCE SCAN`,
    `Bedrijf: ${r(data.bedrijfsnaam)}  |  Datum: ${d}`,
    `Ingevuld door: ${r(data.naam)} (${r(data.functie)})`,
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 1: BEDRIJFSPROFIEL`,
    `${"═".repeat(60)}`,
    `E-mail: ${r(data.email)}`,
    `Telefoon: ${r(data.telefoon)}`,
    `LinkedIn: ${r(data.linkedin)}`,
    `Bedrijfsnaam: ${r(data.bedrijfsnaam)}`,
    `KVK-nummer: ${r(data.kvk)}`,
    `Website: ${r(data.website)}`,
    `Vestigingsplaats: ${r(data.vestigingsplaats)}`,
    `Aantal vestigingen: ${r(data.aantalVestigingen)}`,
    `Sector: ${r(data.sector)}`,
    `Jaaromzet: ${r(data.jaaromzet)}`,
    `Aantal medewerkers: ${r(data.aantalMedewerkers)}`,
    `Bedrijfsstructuur: ${r(data.bedrijfsStructuur)}`,
    ``,
    `Bedrijfsbeschrijving:`,
    r(data.bedrijfsBeschrijving),
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 2: KERNPROCESSEN (${data.processen?.length ?? 0} ingevuld)`,
    `${"═".repeat(60)}`,
    ...(data.processen ?? []).flatMap((p, i) => [
      ``,
      `── Proces ${i + 1}: ${r(p.procesNaam)} ──`,
      `Afdeling: ${r(p.afdeling)}`,
      `Tijdsinvestering: ${TIJD[p.tijdPerMaand ?? ""] ?? r(p.tijdPerMaand)}`,
      `Betrokken mensen: ${r(p.aantalMensen)}`,
      `Tools / systemen: ${r(p.tools)}`,
      `Foutfrequentie: ${FOUTEN[p.foutFrequentie ?? ""] ?? r(p.foutFrequentie)}`,
      `Documentatiestatus: ${DOC[p.documentatieStatus ?? ""] ?? r(p.documentatieStatus)}`,
      `Kosten per fout: ${r(p.kostenPerFout)}`,
      `Urgentie automatisering: ${rating(p.urgentie)}`,
      `Stap-voor-stap beschrijving:`,
      r(p.stapVoorStap),
    ]),
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 3: PIJNPUNTEN & BOTTLENECKS`,
    `${"═".repeat(60)}`,
    `Tijdverlies per week:`,
    r(data.tijdVerliesPerWeek),
    ``,
    `3 grootste frustraties:`,
    r(data.drieGrootsFrustraties),
    ``,
    `Repetitieve taken: ${arr(data.repetitieveTaken)}`,
    `Geschat % repetitief werk: ${r(data.percentageRepetitief)}`,
    ``,
    `Waar gaan fouten mis:`,
    r(data.waarGaanFoutenMis),
    ``,
    `Gevolg van fouten: ${arr(data.gevolgFouten)}`,
    `Foutkosten per maand: ${r(data.foutKostenPerMaand)}`,
    ``,
    `Bedrijfsgroei afgelopen 2 jaar: ${r(data.bedrijfsgroei)}`,
    `Bottlenecks voor groei: ${r(data.bottlenecksGroei)}`,
    `Personeelstekort knelpunt: ${r(data.personeelTekort)}`,
    ``,
    `Als omzet verdubbelt, wat gaat er mis:`,
    r(data.watAlsOmzetVerdubbelt),
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 4: DATA & INFORMATIEBEHEER`,
    `${"═".repeat(60)}`,
    `Waar leeft informatie: ${arr(data.informatieWaarLeeft)}`,
    `Dataconsistentie: ${r(data.dataConsistentie)}`,
    `Vertrouwen in datakwaliteit: ${rating(data.dataVertrouwen)}`,
    `Soorten data: ${arr(data.dataSoorten)}`,
    `Inzicht in bedrijfsprestaties: ${arr(data.inzichtBedrijfsprestaties)}`,
    `Metrics met goed zicht: ${r(data.metricsGoedZicht)}`,
    `Metrics met beter inzicht gewenst: ${r(data.metricsBeterInzicht)}`,
    `Rapportage duurt: ${r(data.rapportageDuur)}`,
    `Documentbeheer: ${arr(data.documentenBeheer)}`,
    `Zoeken duurt gemiddeld: ${r(data.documentZoekenDuur)}`,
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 5: TECHNOLOGIE & SYSTEMEN`,
    `${"═".repeat(60)}`,
    `ERP-gebruik: ${ERP[data.erpGebruik] ?? r(data.erpGebruik)}${data.erpNaam ? ` → ${data.erpNaam}` : ""}`,
    `CRM-gebruik: ${CRM[data.crmGebruik] ?? r(data.crmGebruik)}${data.crmNaam ? ` → ${data.crmNaam}` : ""}`,
    `Boekhoudsoftware: ${arr(data.boekhoudsoftware)}`,
    `Planningsoplossing: ${r(data.planningsoplossing)}${data.planningsSoftwareNaam ? ` → ${data.planningsSoftwareNaam}` : ""}`,
    `Dagelijkse tools: ${arr(data.dagelijkseTools)}`,
    `Interne communicatie: ${arr(data.interneCommunicatie)}`,
    `Aantal systemen: ${r(data.aantalSystemen)}`,
    `Systemen gekoppeld: ${r(data.integraties)}`,
    `Handmatige data-overzet: ${r(data.handmatigeDataOverzet)}`,
    `Automatiseringservaring: ${r(data.automatiseringsErvaring)}`,
    `IT-volwassenheid: ${rating(data.itVolwassenheid)}`,
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 6: KLANTBELEVING & SALES`,
    `${"═".repeat(60)}`,
    `Salesproces:`,
    r(data.salesProces),
    ``,
    `Lead-tot-deal doorlooptijd: ${r(data.leadTotDealDoorlooptijd)}`,
    `Conversieratio: ${r(data.conversieratio)}`,
    `Leads haken af op: ${r(data.leadsAfhaakpunt)}`,
    `Tijd aan offertes per week: ${r(data.tijdOftesPerWeek)}`,
    `Klantvragen per dag: ${r(data.klantvragenPerDag)}`,
    `Reactietijd klant: ${r(data.reactietijdKlant)}`,
    `Soort klantvragen: ${arr(data.soortKlantvragen)}`,
    `Klanttevredenheid (NPS): ${r(data.klanttevredenheidNPS)}`,
    `Klantretentie: ${r(data.klantretentie)}`,
    `Aantal actieve klanten: ${r(data.aantalActieveKlanten)}`,
    `Klantsegmentatie: ${r(data.klantsegmentatie)}`,
    `Upsell / cross-sell: ${r(data.upsellCrossSell)}`,
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 7: TEAM & HR`,
    `${"═".repeat(60)}`,
    `Organisatiestructuur: ${r(data.bedrijfsOrganisatie)}`,
    `Aanwezige rollen: ${arr(data.aanwezigeRollen)}`,
    `% medewerkers met repetitief werk: ${r(data.percentageRepetitieveWerkers)}`,
    `Onboarding duurt: ${r(data.onboardingDuur)}`,
    `Onboarding gestandaardiseerd: ${r(data.onboardingGestandaardiseerd)}`,
    `Houding team t.o.v. AI: ${r(data.teamHoudingAI)}`,
    `Technische affiniteit: ${r(data.technischeAffiniteit)}`,
    `Gebruiksgemak belang: ${rating(data.gebruiksgemakBelang)}`,
    ``,
    `Sleutelmedewerker risico:`,
    r(data.sleutelmedewerkerRisico),
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 8: FINANCIEEL & ROI`,
    `${"═".repeat(60)}`,
    `Grootste kostenpost: ${r(data.grootsteKostenpost)}`,
    `Brutomarge: ${r(data.brutomarge)}`,
    `Gemiddeld uurtarief: ${r(data.gemiddeldUurtarief)}`,
    `Budget voor AI: ${r(data.budgetAI)}`,
    `ROI-beoordeling: ${r(data.roiBeoordeling)}`,
    `Eerdere investeringen: ${r(data.eerdereInvesteringen)}`,
    `Waarde van 40 vrijgemaakte uur: ${r(data.waarde40Uur)}`,
    `Bewijs van succes AI: ${arr(data.bewijsSuccesAI)}`,
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 9: AI-GEREEDHEID`,
    `${"═".repeat(60)}`,
    `Huidige AI-tools: ${arr(data.huidigeAITools)}`,
    `Hoe worden AI-tools gebruikt: ${arr(data.aiGebruikWijze)}`,
    `Begrip van AI-agents: ${r(data.agentBegrip)}`,
    `Comfortniveau AI: ${r(data.comfortNiveauAI)}`,
    `Data toegankelijk voor AI: ${arr(data.dataToegangAI)}`,
    `Sector regelgeving: ${r(data.sectorRegelgeving)}`,
    `Klantdata privacy: ${arr(data.klantdataPrivacy)}`,
    `AI traceerbaarheid belang: ${rating(data.aiTraceerbaarheid)}`,
    ``,
    `Automatiseringskandidaten:`,
    arr(data.automatiseringsKandidaten),
    ``,
    `${"═".repeat(60)}`,
    `SECTIE 10: STRATEGIE & VISIE`,
    `${"═".repeat(60)}`,
    `Belangrijkste doel:`,
    r(data.belangrijksteDoel),
    ``,
    `Top 3 prioriteiten: ${arr(data.topPrioriteiten)}`,
    `Grootste impact verwacht bij: ${r(data.grootsteImpact)}`,
    `Eerste resultaten timeline: ${r(data.eersteResultatenTimeline)}`,
    `Bedrijf over 3 jaar:`,
    r(data.bedrijfOver3Jaar),
    ``,
    `Rol AI in toekomst: ${r(data.rolAIToekomst)}`,
    `AI-expertise beslissing: ${r(data.aiExpertiseBeslissing)}`,
    `Samenwerkingsvorm: ${r(data.samenwerkingsVorm)}`,
    `Startsnelheid: ${r(data.startSnelheid)}`,
    `Aanleiding voor de scan: ${r(data.aanleiding)}`,
    `Eerder met AI-bureau gewerkt: ${r(data.eerderAIBureaus)}`,
    `Hoe gevonden: ${r(data.hoeGevonden)}`,
    ``,
    `Bijzonderheden:`,
    r(data.bijzonderheden),
    ``,
    `${"─".repeat(60)}`,
    `NEXTRIQ · nextriq.nl`,
  ];

  return lines.join("\n");
}
